# Generated by Django 4.0.4 on 2022-05-17 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipousuario',
            old_name='fecha_asignación',
            new_name='fecha_asignacion',
        ),
    ]
