# Generated by Django 4.0.4 on 2022-05-17 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0002_rename_fecha_asignación_equipousuario_fecha_asignacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='equipousuario',
            name='usuario',
            field=models.ForeignKey(limit_choices_to='equipo', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
