# Generated by Django 4.0.4 on 2022-05-17 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0003_equipo_enable_alter_equipousuario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipousuario',
            name='usuario',
            field=models.ForeignKey(limit_choices_to={'enable': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
